### PR TITLE
unicode support

### PR DESCRIPTION
**Pull request by 1d10t**

### CODE REVIEW

**Comment by tzi** [comment]
Hi @1d10t! 

Thanks for the hint about unicode support.
What is your use case?
I'd like to add an associated test and I need to understand for it is for.

Cheers,
Thomas.

**Comment by tzi** [comment]
I added a simple test for unicode support => 0ee4970be2a787383d853003a9d863199f2d529b
But I didn't found what was wrong :disappointed:

**Comment by tzi** [comment]
First commit for this PR was here #38

**Comment by 1d10t** [comment]
hi,
i saw byte-stripping artefacts on cyrillic capitalized chars without 'u' modifier.
now i cant remember which sybmol broken, maybe it was russian R ("Р") at start of text content in tag.

**Comment by tzi** [comment]
Sadly, I can not reproduce it so I will not validate the fix.

But, I'm really interested in unicode support.
If you can reproduce, please, re-open this issue with the html content that do not work.

Thanks again for your hint,
Thomas.

**Pull request closed without merging**
