### PR TITLE
Change <> to [] around email address and url

### PR DESCRIPTION
**Pull request by SL-Gundam**
After letting Markdownify do its job i also use strip_tags to remove any leftover html
strip_tags does not like to <> around urls and email addresses.
It's also possible to change <> to &lt;&gt; but I felt [] might be better.

### CODE REVIEW

**Comment by tzi** [comment]
Hi @SL-Gundam!

Thank you for your PR, but I will not be able to merge it 😞 
Because according [to the specifications](http://spec.commonmark.org/0.27/#autolinks), we can not use brackets to declare autolinks.

We have another solution to prevent you from having remaining HTML in your final markdown. The `setKeepHtml()` method force HTML conversion:

``` php
$converter = new Converter();
$converter->setKeepHTML(false);
echo $converter->parseString('<span><u>Some text</u></span>');
// Output "Some text"
```

Cheers,
Thomas.

**Comment by SL-Gundam** [comment]
setKeepHTML is not enough for me as i still have left over html after that. Emails are bloody html mess.

Is it possible then that we change <> to &lt; &gt; ?

**Comment by tzi** [comment]
No, we can't do that either 😞 

What kind of HTML do you still have left after the conversion?

We're currently having 3 printing options for links (cf https://github.com/Elephant418/Markdownify/blob/master/src/Converter.php#L78).
We can add another option to disable the autolink format.

So instead of `<http://example.com>` we will have `[http://example.com](http://example.com)`.
Would that be OK for you?

**Comment by SL-Gundam** [comment]
Yes it would.

But maybe it would be better if i first collect any left over html and report it here so that i might not even need strip_tags anymore

**Comment by tzi** [comment]
Let's start both actions 👍

**Pull request closed without merging**
